services:
  - type: web
    name: student-portfolio
    runtime: native  # или попробовать этот вариант
    repo: https://github.com/Gleb-er/student-portfolio
    plan: free
    region: oregon
    branch: master
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod