services:
  - type: web
    name: student-portfolio
    runtime: java
    repo: https://github.com/Gleb-er/student-portfolio
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: student-portfolio-db
          property: connectionString
      - key: JAVA_VERSION
        value: 17

databases:
  - name: student-portfolio-db
    plan: free
    databaseName: studentportfolio
    user: studentportfolio_user