services:
  - type: web
    name: student-portfolio
    runtime: java
    repo: https://github.com/Gleb-er/student-portfolio
    plan: free
    region: frankfurt  # или выберите другой регион, например 'singapore'
    branch: master
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: student-portfolio-db
    plan: free
    region: oregon  # должен совпадать с регионом web-сервиса