services:
  - type: web
    name: student-portfolio
    repo: https://github.com/Gleb-er/student-portfolio
    plan: free
    region: oregon
    branch: master
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: student-portfolio-db
    plan: free
    region: oregon